---
title: "S&DS363_PSET_2"
author: "Ethan Mathieu, Tony Ruan, Humrya Karim"
date: "2024-02-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages("biotools")
install.packages("klaR")
install.packages("ggExtra")
install.packages("heplots")
install.packages("rgl")

library(MASS)
library(biotools)
library(klaR)
library(car)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggExtra)
library(heplots, exclude = "rgl")

```

``` {r data_set_up}

GED <- read.csv("Global_Education.csv")

GED_Leveled <- GED |>
   mutate(ed_level = case_when(
    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) < 50 ~ "Low",
    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) >= 50 &
    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) < 80 ~ "Medium",
    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) >= 80 ~ "High"
  )) |>
    select(Completion_Rate_Upper_Secondary_Female, Birth_Rate, ed_level)
    


#GED_Leveled <- GED |>
#   mutate(ed_level = case_when(
#    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) < 80 ~ "Low",
#    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) >= 80 &
#    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) < 90 ~ "Medium",
#    ((Completion_Rate_Upper_Secondary_Male + Completion_Rate_Upper_Secondary_Female) / 2) >= 90 ~ "High"
#  )) |> 
#    mutate(Unemployment_Rate = as.numeric(Unemployment_Rate)) |>
#   mutate(Birth_Rate = as.numeric(Birth_Rate))

#GED

GED_Leveled

```

```{r question_1}

par(mfrow = c(1,2), pty = "s", cex = 0.8)
boxplot(GED_Leveled$Birth_Rate ~ GED_Leveled$ed_level)
boxplot(GED_Leveled$Completion_Rate_Upper_Secondary_Female ~ GED_Leveled$ed_level)
par(mfrow = c(1, 1))

par(mfrow = c(1,3), pty = "s", cex = 0.8)
cqplot(GED_Leveled[GED_Leveled$ed_level == "Low", c("Birth_Rate","Completion_Rate_Upper_Secondary_Female")], main = "Low")
cqplot(GED_Leveled[GED_Leveled$ed_level == "Medium", c("Birth_Rate","Completion_Rate_Upper_Secondary_Female")], main = "Medium")
cqplot(GED_Leveled[GED_Leveled$ed_level == "High", c("Birth_Rate","Completion_Rate_Upper_Secondary_Female")], main = "High")
par(mfrow = c(1, 1))

boxM(GED_Leveled[,c("Birth_Rate", "Completion_Rate_Upper_Secondary_Female")], GED_Leveled$ed_level)

```

```{r question_2}

(GED_Leveled_disc_lda <- lda(GED_Leveled[,1:2], grouping = GED_Leveled$ed_level))
(GED_Leveled_disc_qda <- qda(GED_Leveled[,1:2], grouping = GED_Leveled$ed_level))

```



```{r question_3}

source("http://www.reuningscherer.net/multivariate/R/discrim.r.txt")

discriminant.significance(GED_Leveled[, c("Birth_Rate", "Completion_Rate_Upper_Secondary_Female")], GED_Leveled$ed_level)

```

``` {r question_4}


``` 

